export const CHANGE_GLOBAL_UNIT = "CHANGE_GLOBAL_UNIT";
export const CHANGE_GLOBAL_SYSTEM = "CHANGE_GLOBAL_SYSTEM";
export const TOGGLE_AUTO_CONVERT = "TOGGLE_AUTO_CONVERT";
export const EDIT_RECIPE = "EDIT_RECIPE";